PictureGallery/PictureGallery/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PictureGallery.Data;

namespace PictureGallery.Models
{
    public class AlbumsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AlbumsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Albums
        public async Task<IActionResult> Index()
        {
            // Muudetud, järgmine rida pooleli. Tekita Useritest list, data value field ja text field
            var albums = _context.Album
                .Include(x => x.Favorites)
                .Include(p => p.User);
            // Küsib praeguse kasutaja
            ClaimsPrincipal currentUser = this.User;
            // Kui praegu ei ole ükski kasutaja sisse loginud
            if (currentUser.Identity.Name == null)
            {
                return View(await albums.ToListAsync());
            }
            // Salvestab UserId väärtuse
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.CurrentUserId = currentUserId;
            foreach (var album in albums)
            {
                var currentFavorite = album.Favorites.Where(x => x.UserId == currentUserId).FirstOrDefault();
                if (currentFavorite != null)
                {
                    album.IsFavorite = currentFavorite.IsFavorite;
                }
            }
            return View(await albums.ToListAsync());
        }

        // uus Index action
        public IActionResult MyIndex()
        {
            // Küsib praeguse kasutaja
            ClaimsPrincipal currentUser = this.User;
            // Kui praegu ei ole ükski kasutaja sisse loginud
            if (currentUser.Identity.Name == null)
            {
                return View(_context.Album.ToList());
            }
            // Salvestab UserId väärtuse
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            List<Album> Albums = new List<Album>();
            // Võta ainult need albumid, mis on praeguse kasutaja omad
            Albums = _context.Album.Where(x => x.UserId == currentUserId).ToList();
            return View(Albums);
        }

        // GET: Albums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var album = await _context.Album
                .Include(x => x.User)
                .Include(x => x.Pictures)
                .Include(x => x.Favorites)
                .FirstOrDefaultAsync(m => m.Id == id);
            album.Pictures = album.Pictures.OrderByDescending(x => x.DateCreated).ToList();
            if (album == null)
            {
                return NotFound();
            }

            ClaimsPrincipal currentUser = this.User;
            if (currentUser.Identity.Name == null)
            {
                return View(album);
            }
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.CurrentUserId = currentUserId;
            if (album.Favorites != null)
            {
                var currentFavorite = album.Favorites.Where(x => x.UserId == currentUserId).FirstOrDefault();
                if (currentFavorite != null)
                {
                    album.IsFavorite = currentFavorite.IsFavorite;
                }
            }


            return View(album);
        }

        // GET: Albums/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,UserId,DateCreated")] Album album)
        {
            if (ModelState.IsValid)
            {
                // Küsib praeguse kasutaja
                ClaimsPrincipal currentUser = this.User;
                // Salvestab UserId väärtuse
                album.UserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

                _context.Add(album);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(MyIndex));
            }
            return View(album);
        }

        // GET: Albums/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Album.FindAsync(id);
            if (album == null)
            {
                return NotFound();
            }
            return View(album);
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,UserId,DateCreated")] Album album)
        {
            if (id != album.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    // Muudetakse ainult albumi title
                    Album config = _context.Album.Find(album.Id);
                    config.Title = album.Title;
                    await _context.SaveChangesAsync();
                    //_context.Update(album);
                    //await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlbumExists(album.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(MyIndex));
            }
            return View(album);
        }

        // GET: Albums/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Album
                .FirstOrDefaultAsync(m => m.Id == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var album = await _context.Album.FindAsync(id);
            _context.Album.Remove(album);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(MyIndex));
        }

        private bool AlbumExists(int id)
        {
            return _context.Album.Any(e => e.Id == id);
        }
    }
}

PictureGallery/PictureGallery/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PictureGallery.Data;
using PictureGallery.Models;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;

namespace PictureGallery.Controllers
{
    public class PicturesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PicturesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pictures
        public async Task<IActionResult> Index()
        {
            // Näita Albumi Id asemel Albumi Title
            var applicationDbContext = _context.Picture
                .Include(p => p.Album).Include(x => x.Likes).OrderByDescending(x => x.DateCreated);
            var pictures = await applicationDbContext.ToListAsync();

            // Küsib praeguse kasutaja
            ClaimsPrincipal currentUser = this.User;
            // Kui praegu ei ole ükski kasutaja sisse loginud
            if (currentUser.Identity.Name == null)
            {
                return View(_context.Picture.ToList());
            }
            // Salvestab UserId väärtuse
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.CurrentUserId = currentUserId;

            foreach (var picture in pictures)
            {
                picture.AmountOfLikes =  picture.Likes.Where(x => x.IsLiked).Count();
                var currentLike = picture.Likes.Where(x => x.UserId == currentUserId).FirstOrDefault();
                if (currentLike != null)
                {
                    picture.IsLiked = currentLike.IsLiked;
                }
            }
            return View(pictures);
        }


        // uus Index action
        public IActionResult MyIndex()
        {
            // Küsib praeguse kasutaja
            ClaimsPrincipal currentUser = this.User;
            if (currentUser.Identity.Name == null)
            {
                return View(_context.Picture.ToList());
            }
            // Salvestab UserId väärtuse
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            ViewBag.CurrentUserId = currentUserId;
            List<Picture> Pictures = new List<Picture>();
            // Võta ainult need albumid, mis on praeguse kasutaja omad ja lisa albumid kaasa
            Pictures = _context.Picture
                .Where(x => x.Album.UserId == currentUserId)
                .Include(x => x.Album).OrderByDescending(x => x.DateCreated)
                .ToList();
            
            return View(Pictures);
        }
        // GET: Pictures/Details/5
        public IActionResult Details(int? id, int? albumId)
        {
            if (id == null)
            {
                return NotFound();
            }
            var pictures = _context.Picture
                .Include(x => x.Comments).ThenInclude(x => x.User)
                .Include(x => x.Album).ThenInclude(x => x.User)
                .Include(x => x.Likes)
                .OrderByDescending(x => x.DateCreated).ToList();
            if(albumId != null)
            {
                pictures = pictures.Where(x => x.Album.Id == albumId).ToList();
            }

            var picture = pictures.FirstOrDefault(m => m.Id == id);
            if (picture == null)
            {
                return NotFound();
            }
            picture.Comments = picture.Comments.OrderByDescending(x => x.DateCreated).ToList();
            //List<Picture> Pictures = new List<Picture>();
            //Pictures = _context.Picture.Where(x => x.Album.UserId == currentUserId).Include(x => x.Album).OrderByDescending(x => x.DateCreated).ToList();

            var currentPictureIndex = pictures.IndexOf(picture);
            if (currentPictureIndex > 0)
            {
                ViewBag.PreviousPictureId = pictures[pictures.IndexOf(picture) - 1].Id;
            }

            if (currentPictureIndex != pictures.Count-1)
            {
                ViewBag.NextPictureId = pictures[pictures.IndexOf(picture) + 1].Id;
            }
            if (albumId != null)
            {
                ViewBag.AlbumId = albumId;
            }

            ClaimsPrincipal currentUser = this.User;
            if (currentUser.Identity.Name == null)
            {
                return View(picture);
            }
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.CurrentUserId = currentUserId;
            if (picture.Likes != null)
            {
                var currentLike = picture.Likes.Where(x => x.UserId == currentUserId).FirstOrDefault();
                if (currentLike != null)
                {
                    picture.IsLiked = currentLike.IsLiked;
                }
            }
            return View(picture);
        }

        // Tagastab suure pildi
        public IActionResult GetImageFile(int pictureId)
        {
            //Kui picture on tühi, siis tagastab stringi "Pilti pole"
            var picture = _context.Picture.Find(pictureId);
            if (picture == null || picture.Image == null)
            {
                return Content("Picture not found.");
            }
            return File(picture.Image, "image/jpg");
        }
        // Tagastab thumbi või kui seda ei ole, siis suure pildi
        public IActionResult GetThumbnail(int pictureId)
        {
            var picture = _context.Picture.Find(pictureId);
            if (picture == null)
            {
                return Content("Picture not found.");
            }
            else if (picture.ImageThumbnail == null)
            {
                return GetImageFile(pictureId);
            }
            return File(picture.ImageThumbnail, "image/jpg");
        }

        // POST: Pictures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveComment(int pictureId, string commentText)
        {
            ClaimsPrincipal currentUser = this.User;
            // Salvestab UserId väärtuse
            var comment = new Comment();
            if (commentText == null)
            {
                // Kui kommentaari väli on tühi, siis seda ei lisata
                ModelState.AddModelError("", "Please type a comment.");
                return RedirectToAction(nameof(Details), new { Id = pictureId });

            }
            comment.Content = commentText;
            comment.PictureId = pictureId;
            if (currentUser.Identity.Name != null)
            {
                comment.UserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
            _context.Add(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), new { Id = pictureId });

        }

        // GET: Pictures/Create
        public IActionResult Create(int albumId)
        {
            // Pilt läheb sellesse albumisse, mille alt ta lisatakse
            ViewData["AlbumId"] = albumId;
            return View();
        }

        // POST: Pictures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Image,ImageThumbnail,AlbumId,DateCreated")] Picture picture, IFormFile image)
        {
            var albumId = picture.AlbumId;
            ViewData["AlbumId"] = albumId;
            if (image == null)
            {
                ModelState.AddModelError("", "Image file required");
                return View(picture);
            }
            if (ModelState.IsValid)
            {

                MemoryStream stream = new MemoryStream();
                image.CopyTo(stream);

                IImageFormat format;
                // Max mõõtudest suurema pildi vähendamine
                using (Image<Rgba32> imageToResize = Image.Load(stream.ToArray(), out format))
                {
                    stream = new MemoryStream();
                    if (imageToResize.Width > 800)
                    {
                        imageToResize.Mutate(x => x.Resize(800, 0));
                    }
                    if (imageToResize.Height > 600)
                    {
                        imageToResize.Mutate(x => x.Resize(0, 600));
                    }
                    imageToResize.Save(stream, format);
                }
                picture.Image = stream.ToArray();

                //Thumbi genereerimine. Peab olema vähemalt 350 x 250 px ja piirav mõõt peab olema täpne
                using (Image<Rgba32> imageToResize = Image.Load(stream.ToArray(), out format))
                {
                    stream = new MemoryStream();
                    if (imageToResize.Width/(double)imageToResize.Height > 1.4 )
                    {
                        imageToResize.Mutate(x => x.Resize(0, 250));
                    }
                    else
                    {
                        imageToResize.Mutate(x => x.Resize(350, 0));
                    }
                    imageToResize.Save(stream, format);
                }
                picture.ImageThumbnail = stream.ToArray();
                stream.Close();

                _context.Add(picture);
                await _context.SaveChangesAsync();

PictureGallery/PictureGallery/Views/Albums/Create.cshtml
@model PictureGallery.Models.Album

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Album</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="MyIndex">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PictureGallery/PictureGallery/Views/Albums/Delete.cshtml
@model PictureGallery.Models.Album

@{
    ViewData["Title"] = "Delete";
}

<h2>@Model.Title</h2>

<h3>Are you sure you want to delete this album?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="MyIndex">Back to List</a>
    </form>
</div>

PictureGallery/PictureGallery/Views/Albums/Details.cshtml
@model PictureGallery.Models.Album

@{
    ViewData["Title"] = Model.Title;
}

<h2> @Html.DisplayFor(model => model.Title)</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
            @Html.DisplayFor(model => model.User.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        @if (ViewBag.CurrentUserId != null)
        {
            <td>
                @{
                    var idFaveBtn = "favebutton_" + Model.Id;
                }
                @if (Model.IsFavorite)
                {
                    <button id='@idFaveBtn' class="buttonIsFavoriteActive">FAVED</button>
                }
                else
                {
                    <button id='@idFaveBtn' class="buttonIsFavorite">Favorite</button>
                }
            </td>
        }
    </dl>
    <hr />
</div>
@foreach (var item in Model.Pictures)
{
    <a asp-controller="Pictures" asp-action="Details" asp-route-id="@item.Id" asp-route-albumId="@Model.Id">
        <img class="cover" src=@Url.Action("GetThumbnail", "Pictures", new { pictureId = item.Id }) />
    </a>
}

<div>
    @if (Model.User != null && Model.User.Id == ViewBag.CurrentUserId)
    {
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit </a> <text>|</text>
    }
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
            $(document).on('click', '.buttonIsFavorite', function (event) {
                event.preventDefault();
                if ($(this).hasClass('buttonIsFavorite')) {
                    $(this).removeClass('buttonIsFavorite');
                    $(this).addClass('buttonIsFavoriteActive');
                }

        var id = this.id;
            $.ajax({
                type: 'POST',
                url: "/Favorites/FavoriteCheck/",
                data: {
                    albumId: id.replace("favebutton_", ""),
                    isFavorite: $(this).hasClass('buttonIsFavoriteActive'),
                    userId : '@ViewBag.CurrentUserId'
                },
                success: function (result) {
                    var tr = "<td>"
                    tr += "<td>" + result.isFavorite + "</td>";
                }
            });
        });
        $(document).on('click', '.buttonIsFavoriteActive', function (event) {
            event.preventDefault();
            if ($(this).hasClass('buttonIsFavoriteActive')) {
                $(this).removeClass('buttonIsFavoriteActive');
                $(this).addClass('buttonIsFavorite');
            }

            var id = this.id;
            $.ajax({
                type: 'POST',
                url: "/Favorites/FavoriteCheck/",
                data: {
                    albumId: id.replace("favebutton_", ""),
                    isFavorite: $(this).hasClass('buttonIsFavoriteActive'),
                    userId: '@ViewBag.CurrentUserId'
                },
                success: function (result) {
                    var tr = "<tr>"
                    tr += "<td>" + result.isFavorite + "</td>";
                }
            });
            });
        });
    </script>
}

PictureGallery/PictureGallery/Views/Albums/Index.cshtml
@model IEnumerable<PictureGallery.Models.Album>

@{
    ViewData["Title"] = "All albums";
}

<h3>All albums</h3>

<table class="table" id="allAlbums">
    <thead>
        <tr>
            @*<th id="albumcoverpic">
                albumcoverpic
            </th>*@
            <th id="title">
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th id="userId">
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th id="dateCreated">
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            @if (ViewBag.CurrentUserId != null)
            {
                <th id="isFavorite">
                    @Html.DisplayNameFor(model => model.IsFavorite)
                </th>
            }
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            @*<td>
                siin peaks olema
            </td>*@
            <td>
                <a asp-controller="Albums" asp-action="Details" asp-route-id="@item.Id">
                    @item.Title
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.FirstName)
                @Html.DisplayFor(modelItem => item.User.LastName)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            @if (ViewBag.CurrentUserId != null)
            {
                <td>
                    @{
                        var idFaveBtn = "favebutton_" + item.Id;
                    }
                    @if (item.IsFavorite)
                    {
                        <button id='@idFaveBtn' class="buttonIsFavoriteActive">FAVED</button>
                    }
                    else
                    {
                        <button id='@idFaveBtn' class="buttonIsFavorite">Favorite</button>
                    }
                </td>
            }
        </tr>
        }
    </tbody>
</table>

@section Scripts
    {
    <script type="text/javascript">

        function sortTable(f, n) {
            var rows = $('#allAlbums tbody  tr').get();

            rows.sort(function (a, b) {

                var A = getVal(a);
                var B = getVal(b);

                if (A < B) {
                    return -1 * f;
                }
                if (A > B) {
                    return 1 * f;
                }
                return 0;
            });

            function getVal(elm) {
                var v = $(elm).children('td').eq(n).text().toUpperCase();
                if ($.isNumeric(v)) {
                    v = parseInt(v, 10);
                }
                return v;
            }

            $.each(rows, function (index, row) {
                $('#allAlbums').children('tbody').append(row);
            });
        }
        var f_title = 1;
        var f_userId = 1;
        var f_dateCreated = 1;
        var f_isFavorite = 1;


        $("#title").click(function () {
            f_title *= -1;
            var n = $(this).prevAll().length;
            sortTable(f_title, n);
        });
        $("#userId").click(function () {
            f_userId *= -1;
            var n = $(this).prevAll().length;
            sortTable(f_userId, n);
        });
        $("#dateCreated").click(function () {
            f_dateCreated *= -1;
            var n = $(this).prevAll().length;
            sortTable(f_dateCreated, n);
        });
        $("#isFavorite").click(function () {
            f_isFavorite *= -1;
            var n = $(this).prevAll().length;
            sortTable(f_isFavorite, n);
        });

        $(document).ready(function () {
            $(document).on('click', '.buttonIsFavorite', function (event) {
                event.preventDefault();
                if ($(this).hasClass('buttonIsFavorite')) {
                    $(this).removeClass('buttonIsFavorite');
                    $(this).addClass('buttonIsFavoriteActive');
                }
                //$(this).toggleClass('buttonIsLikedActive');

                var id = this.id;
                $.ajax({
                    type: 'POST',
                    url: "/Favorites/FavoriteCheck/",
                    data: {
                        albumId: id.replace("favebutton_", ""),
                        isFavorite: $(this).hasClass('buttonIsFavoriteActive'),
                        userId : '@ViewBag.CurrentUserId'
                    },
                    success: function (result) {
                        var tr = "<tr>"
                        tr += "<td>" + result.isFavorite + "</td>";
                    }
                });
            });
            $(document).on('click', '.buttonIsFavoriteActive', function (event) {
                event.preventDefault();
                if ($(this).hasClass('buttonIsFavoriteActive')) {
                    $(this).removeClass('buttonIsFavoriteActive');
                    $(this).addClass('buttonIsFavorite');

                }
                //$(this).toggleClass('buttonIsLikedActive');

                var id = this.id;
                $.ajax({
                    type: 'POST',
                    url: "/Favorites/FavoriteCheck/",
                    data: {
                        albumId: id.replace("favebutton_", ""),
                        isFavorite: $(this).hasClass('buttonIsFavoriteActive'),
                        userId: '@ViewBag.CurrentUserId'
                    },
                    success: function (result) {
                        var tr = "<tr>"
                        tr += "<td>" + result.isFavorite + "</td>";
                    }
                });
            });
        });
    </script>
}

PictureGallery/PictureGallery/Views/Albums/MyIndex.cshtml
@model IEnumerable<PictureGallery.Models.Album>

@{
    ViewData["Title"] = "My albums";
}

<h3>My albums</h3>

<p>
    <a asp-action="Create"><img src="~/images/addalb.png"
     alt="Add new album" height="50" width="50" /></a>
</p>

@* vaja veel, et ühe albumi all oleks Create New picture *@
<table class="table" id="myAlbums">
    <thead>
        <tr>
            <th id="title">
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th id="dateCreated">
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                Settings
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @*siin peaks olema albumi coverpic*@
                @*<a>

                <img class="cover" src=@Url.Action("GetThumbnail", "Pictures", new { pictureId = item.Id, }) />
            </a>*@
                <a asp-controller="Pictures" asp-action="Create" asp-route-albumId="@item.Id">
                    <img src="~/images/addimg.png"
                         alt="Add new picture" height="50" width="50" />
                </a>
                <a>
                </a>
                <a asp-action="Details" asp-route-id="@item.Id">
                    @item.Title
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit title</a> |

                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>


        </tr>
        }
    </tbody>
</table>



@section Scripts
    {
    <script type="text/javascript">

        function sortTable(f, n) {
            var rows = $('#myAlbums tbody  tr').get();

            rows.sort(function (a, b) {

                var A = getVal(a);
                var B = getVal(b);

                if (A < B) {
                    return -1 * f;
                }
                if (A > B) {
                    return 1 * f;
                }
                return 0;
            });

            function getVal(elm) {
                var v = $(elm).children('td').eq(n).text().toUpperCase();
                if ($.isNumeric(v)) {
                    v = parseInt(v, 10);
                }
                return v;
            }

            $.each(rows, function (index, row) {
                $('#myAlbums').children('tbody').append(row);
            });
        }
        var f_title = 1;
        var f_userId = 1;
        var f_dateCreated = 1;

        $("#title").click(function () {
            f_title *= -1;
            var n = $(this).prevAll().length;
            sortTable(f_title, n);
        });
        $("#dateCreated").click(function () {
            f_dateCreated *= -1;
            var n = $(this).prevAll().length;
            sortTable(f_dateCreated, n);
        });

    </script>
}